server:
  port: 8081
spring:
  servlet:
    multipart:
      # 上传文件大小设置
      enabled: true #是否启用http上传处理
      max-request-size: 1024MB #最大请求文件的大小
      max-file-size: 1024MB #设置单个文件最大长度
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///database_shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: xian123
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 100
      max-lifetime: 30000
      connection-timeout: 30000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: xyz.slienceme.clockin.dto
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
logging:
  file:
    path: log