spring:
  path:
    url: https://blog.slienceme.xyz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 100
      max-lifetime: 180000
      connection-timeout: 30000
      idle-timeout: 60000
  redis:
    host: 127.0.0.1
  config:
    activate:
      on-profile: pro
